column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
# call_parentheses = "Always"
call_parentheses = "None"
no_call_parentheses = false

[sort_requires]
enabled = true
